syscall_intercept: detect more references to the text section
marcinslusarz/pmdk pull request #52
Opened 2017-01-19 17:19 UTC by GBuella

2017-01-19 17:26 UTC, marcinslusarz requested changes

2017-01-19 17:26 UTC, marcinslusarz commented on src/libsyscall_intercept/disasm_wrapper.h
> +	 * such references, computed based on the rip_disp.
s/references/reference/

2017-01-19 17:26 UTC, marcinslusarz commented on src/libsyscall_intercept/disasm_wrapper.c
> +	 * execution if this instruction
s/if/of/

2017-01-20 11:26 UTC, GBuella commented
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libsyscall_intercept/disasm_wrapper.c, line 111 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/52#-KarjQgqI9aEGX7VfRDC-r1-111:-KavcDl6svmSblFwk3la:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/5bbb13e9f0d5a47a6bfb865ec2af662e0b6b06f3/src/libsyscall_intercept/disasm_wrapper.c#L111)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/if/of/
</blockquote></details>

Done.

---

*[src/libsyscall_intercept/disasm_wrapper.h, line 85 at r1](https://reviewable.io:443/reviews/marcinslusarz/nvml/52#-KarjQgqI9aEGX7VfRDD-r1-85:-KavcFGTsj2ZjUJzqZay:b-896fix) ([raw file](https://github.com/marcinslusarz/nvml/blob/5bbb13e9f0d5a47a6bfb865ec2af662e0b6b06f3/src/libsyscall_intercept/disasm_wrapper.h#L85)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/references/reference/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/nvml/52)*
<!-- Sent from Reviewable.io -->

2017-01-20 11:51 UTC, marcinslusarz approved these changes

2017-01-20 11:51 UTC, merged